'''  To keep project level configuration like file path etc.. 
of the enviornment(env)like Local- for developement,Test for testing and Prod for production'''

[LOCAL]
customers.file.path = data/customers.csv
orders.file.path = data/orders.csv

[TEST]
customers.file.path = data/customers.csv
orders.file.path = data/orders.csv

[PROD]
customers.file.path = data/customers.csv
orders.file.path = data/orders.csv